[package]
name = "invaderlib"
version = "0.1.0"
authors = ["Jayson Lennon <jay.dub.lennon@gmail.com>"]

[dependencies]
image = "0.10.4"
rand = "0.3.15"
num = "0.1.36"

[dev-dependencies]
stainless = "*"